import type { Metadata } from "next";
import { Geist, Geist_Mono, Edu_SA_Beginner } from "next/font/google";
import "./globals.css";

const edu = Edu_SA_Beginner({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-edu",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ayuns Birthday 25th 💐🎉🥳",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${edu.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
